apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mlflow-db
  namespace: developer-platform
  labels:
    app.kubernetes.io/name: mlflow-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: developer-platform
spec:
  serviceName: mlflow-db
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlflow-db
    spec:
      containers:
      - name: postgres
        image: postgres:15.5
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: mlflow-db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-db-credentials
              key: password
        - name: POSTGRES_DB
          value: mlflow
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
          initialDelaySeconds: 30
          periodSeconds: 20
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-db
  namespace: developer-platform
  labels:
    app.kubernetes.io/name: mlflow-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: developer-platform
spec:
  ports:
  - port: 5432
    targetPort: postgresql
    name: postgresql
  selector:
    app.kubernetes.io/name: mlflow-db 