apiVersion: v1
kind: Secret
metadata:
  name: mlflow-db-credentials
  namespace: developer-platform
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: developer-platform
type: Opaque
stringData:
  username: mlflow
  password: ${MLFLOW_DB_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-gcp-credentials
  namespace: developer-platform
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: developer-platform
type: Opaque
stringData:
  key.json: ${GCP_SERVICE_ACCOUNT_KEY} 