apiVersion: v1
kind: ServiceAccount
metadata:
  name: feature-server-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: feature-server@${GCP_PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: feature-server-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: feature-server-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: feature-server-sa
  namespace: default
roleRef:
  kind: Role
  name: feature-server-role
  apiGroup: rbac.authorization.k8s.io 