repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-black
    - id: nbqa-isort

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0
  hooks:
    - id: prettier
      types_or: [javascript, jsx, ts, tsx, json, yaml] 