apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyterhub-config
  namespace: developer-platform
data:
  jupyterhub_config.py: |
    # Existing JupyterHub config...
    
    # Environment variables for all user pods
    c.KubeSpawner.environment = {
        'MLFLOW_TRACKING_URI': f'https://mlflow.{os.environ["DOMAIN"]}',
        'MLFLOW_TRACKING_INSECURE_TLS': 'false',
    }
    
    # Default packages for all users
    c.KubeSpawner.extra_containers = [{
        'name': 'environment-setup',
        'image': 'python:3.9',
        'command': ['sh', '-c'],
        'args': [
            'pip install mlflow>=2.10.2 google-cloud-storage>=2.14.0 && tail -f /dev/null'
        ],
        'volumeMounts': [
            {
                'name': 'python-packages',
                'mountPath': '/usr/local/lib/python3.9/site-packages'
            }
        ]
    }]
    
    c.KubeSpawner.volumes = [
        {
            'name': 'python-packages',
            'emptyDir': {}
        }
    ]
    
    c.KubeSpawner.volume_mounts = [
        {
            'name': 'python-packages',
            'mountPath': '/usr/local/lib/python3.9/site-packages'
        }
    ] 